// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxexwdbzwvkdtgxqwpya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4ZXh3ZGJ6d3ZrZHRneHF3cHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTQxMzIsImV4cCI6MjA2MTk3MDEzMn0.eXrUxDsIz1ld-HPTO-xJurtR9o_H86zgeWDHs0llAPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);